// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL3sQkkEwM9v8OIq2S3kujntEHzlP-JRw',
    appId: '1:484619974390:web:3762d8eec86b5af6e2ded7',
    messagingSenderId: '484619974390',
    projectId: 'trainy-39fd1',
    authDomain: 'trainy-39fd1.firebaseapp.com',
    storageBucket: 'trainy-39fd1.firebasestorage.app',
    measurementId: 'G-L2FXRJYLQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFZVBCDE0TGBztR5iOLNLGHhUK3VTZJkg',
    appId: '1:484619974390:android:81c843bd6df54d5be2ded7',
    messagingSenderId: '484619974390',
    projectId: 'trainy-39fd1',
    storageBucket: 'trainy-39fd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSDyoZISbWSwUMEB5_2jDSDuwa2kfzWpI',
    appId: '1:484619974390:ios:8bb7f2808a7f1efbe2ded7',
    messagingSenderId: '484619974390',
    projectId: 'trainy-39fd1',
    storageBucket: 'trainy-39fd1.firebasestorage.app',
    iosClientId: '484619974390-q6abavc7b2aejfp2rm74ckgsh4i40198.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainy',
  );
}
